feat: add logging to start runner script.
github-aws-runners/terraform-aws-github-runner pull request #3449
Opened 2023-08-23 16:29 UTC by GuptaNavdeep1983

2023-08-24 06:24 UTC, npalm requested changes
The idea looks good to add support to enable activating logging in this way. It gives an option to enable debug logging without rebuilding an AMI. Pleas can you update the PR description with better reasoning why adding this feature?

2023-08-24 06:24 UTC, npalm commented on lambdas/functions/control-plane/src/scale-runners/scale-up.ts
> +    logLevel: process.env.LOG_LEVEL || 'info',
I think we should stop with reading prcoess.env enverywhre. This is not helping the complexity and understanding wht is happening where. In. this case it is even not needed to read the value from the environment. You can simply request the level in `runner.ts` bij `logger.getLogLevel()`.

2023-08-24 06:24 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +log_level=$(curl -f -H "X-aws-ec2-metadata-token: $token" -v http://169.254.169.254/latest/meta-data/tags/instance/ghr:log_level || echo "")
The user-data script already read a variable log level. This code should move to the wrapper. And merged with the flag enableUserdataLogging.

2023-08-24 06:24 UTC, npalm commented on lambdas/functions/control-plane/src/aws/runners.d.ts
> +  logLevel?: string;
Not needed, loglevel can be obtained via the logger. See other comments

2023-09-01 12:37 UTC, GuptaNavdeep1983 commented on lambdas/functions/control-plane/src/aws/runners.d.ts
> +  logLevel?: string;
removed

2023-10-19 14:53 UTC, npalm commented
@GuptaNavdeep1983 what shall we do with this PR?

2023-11-30 01:48 UTC, closed without merging