feat: add error metrics to instance at start up to create a metric.
github-aws-runners/terraform-aws-github-runner pull request #3478
Opened 2023-09-13 16:55 UTC by GuptaNavdeep1983

2023-09-14 16:03 UTC, npalm requested changes

2023-09-14 16:03 UTC, npalm commented on modules/runners/templates/start-runner.sh
> +}
This part is now duplicated, or not. Maybe we can add a function terminate and invoke it on both places

2023-09-25 06:45 UTC, npalm commented
@GuptaNavdeep1983 did you had time for this PR?

2023-10-30 07:59 UTC, npalm commented
@GuptaNavdeep1983 What should we do with this PR?

2023-12-01 23:45 UTC, GuptaNavdeep1983 commented on modules/runners/templates/start-runner.sh
> +      --namespace "Github Runners metrics" \
This is not the health metric. Its created only on error which should be resolved immediately. I dont think it should be costly. I can remove the permissions (CloudWatch:PutMetricData) to put metric data conditionally  and let this call fail (with fail trap) in the absence of permissions. Do you find that okay?

2024-01-12 01:48 UTC, closed without merging