Pass enable_runner_workflow_job_labels variable to submodule
github-aws-runners/terraform-aws-github-runner pull request #4195
Opened 2024-10-21 13:58 UTC by Yethal

2024-11-01 07:58 UTC, npalm commented
@Yethal just wondering, already had time to work on this PR and get it in ready for review state?

2024-11-01 09:50 UTC, Yethal commented
@npalm Honestly I don't even remember what was left to do here

2024-11-01 11:36 UTC, npalm commented
What problem are you trying to fix. I think the parameter is used only by the webhook module.

2024-11-01 13:41 UTC, Yethal commented
It doesn't work in multi-runner submodule without this change

2024-11-04 08:54 UTC, npalm commented
> It doesn't work in multi-runner submodule without this change

Please can you have a look on the CI, the change is ginving errors on the mult-runner examples

2024-11-15 21:09 UTC, npalm commented
@Yethal kind reminder the CI is broken as result of the PR. Would be great if you can have a look. In the mean time I move the PR in draft status. Please mark ready to review when you ar ready.

2024-11-20 15:57 UTC, npalm commented on modules/multi-runner/runners.tf
> +  runner_labels                               = sort(distinct(concat(["self-hosted", each.value.runner_config.runner_os, each.value.runner_config.runner_architecture], each.value.runner_config.runner
Please can you rebase and accept changes from main, this change should remain.

2024-11-20 15:58 UTC, npalm commented on modules/runners/variables.tf
> +variable "enable_runner_workflow_job_labels_check_all" {
Can you move this to the runner config, so it can be set per runner group.

2024-12-20 08:56 UTC, npalm requested changes
did you had time to had a look on my comments?

2024-12-20 09:13 UTC, Yethal commented
Not really no, in the end I decided to stop using GHA altogether for the project I needed this for. If someone else wants to pick this up feel free

2024-12-20 10:20 UTC, npalm commented
> Not really no, in the end I decided to stop using GHA altogether for the project I needed this for. If someone else wants to pick this up feel free

thx for the reply

2025-03-04 20:45 UTC, closed without merging