fix(runner-install): correct detection of Ubuntu 24.04
github-aws-runners/terraform-aws-github-runner pull request #4246
Opened 2024-11-08 13:34 UTC by bdellegrazie

On Ubuntu 24.04 there is another variable `ID_LIKE` that appears in the `/etc/os-release` file. This change fixes the regex match to only match ID and not ID_LIKE

closes #4245

2024-11-08 13:56 UTC, davidgp1701 approved these changes

2024-11-15 15:39 UTC, npalm reviewed
@bdellegrazie great to see support for ubuntu 24.04 is coming in. What is the status of the PR? How did you test the PR. Is the cahnge working as well for ubuntu 22.04

2024-11-15 16:59 UTC, npalm commented
Just testing the setup on ubuntu 22.04, works all fine. Still curious if there are any side effects. 

Are you also aware we thinking about update the module to support ubuntu by default, and step away from Amazon. Interally we are already 1.5 year on Ubuntu (own ami). Would be great if we can add via a second PR support for arm as well. 

I have updated the examples, will push them asap.

2024-11-15 17:10 UTC, npalm commented
Getting the following error / warning in the log for ubuntu 24.0, however the runner gets healthy online and is being able run jobs.

```

No VM guests are running outdated hypervisor (qemu) binaries on this host.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libssl1.1$
E: Couldn't find any package by glob 'libssl1.1$'
E: Couldn't find any package by regex 'libssl1.1$'
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libssl1.0.2$
E: Couldn't find any package by glob 'libssl1.0.2$'
E: Couldn't find any package by regex 'libssl1.0.2$'
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libssl1.0.0$
E: Couldn't find any package by glob 'libssl1.0.0$'
E: Couldn't find any package by regex 'libssl1.0.0$'
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu72
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu71
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu70
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu69
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu68
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu67
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu66
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu65
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu63
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu60
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu57
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu55
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu52

```

2024-11-15 17:21 UTC, npalm commented
I have pushed changes on the example dir to this branch

2024-11-15 17:24 UTC, npalm commented
In summary:

- multi-runner example contains an ubuntu2404
- really nice contribution 🚀 
- would be great when you can add some details about choices in changes in the user_data example

2024-11-16 18:45 UTC, bdellegrazie commented on examples/multi-runner/templates/user-data.sh
> +apt-get -q -y install docker-ce docker-ce-cli containerd.io docker-ce-rootless-extras docker-buildx-plugin docker-compose-plugin
According to to [docker ubuntu install using the repository](https://docs.docker.com/engine/install/ubuntu/#install-using-the-repository)
yes

2024-11-16 19:07 UTC, bdellegrazie commented on examples/multi-runner/templates/user-data.sh
> +mkdir -p /etc/systemd/system/user-$user_id.slice.d
Yes, attempting to override `user@UID.service` did not work for Ubuntu 24.04 to set the NPROCS / NOFILES settings.

At best we could supply a default that would apply to _all_ users but I think this matches the original intent.
Defaults for users are set in [systemd-users.conf](https://www.freedesktop.org/software/systemd/man/latest/systemd-user.conf.html) which allows a user specific override `~/.config/systemd/user.conf`, so we set the NPROC / NOFILE settings there.

[systemd-slice.conf](https://www.freedesktop.org/software/systemd/man/latest/systemd.resource-control.html#Setting%20resource%20controls%20for%20a%20group%20of%20related%20units) allows user specific overrides of the resource control settings.

I _haven't_ verified that these work with Ubuntu 22.04 or 20.04, it is likely that it will depend entirely upon the systemd version.

2024-11-16 19:08 UTC, bdellegrazie commented on examples/multi-runner/templates/user-data.sh
> +echo export XDG_RUNTIME_DIR="/run/user/$user_id" >> "/home/$user_name/.bashrc"
Yes, it's where docker will store any PID / runtime information for the daemon.
It was there in the original file, I simply moved it.

2024-11-16 19:11 UTC, bdellegrazie commented
> Getting the following error / warning in the log for ubuntu 24.0, however the runner gets healthy online and is being able run jobs.
> 
> ```
> 
> No VM guests are running outdated hypervisor (qemu) binaries on this host.
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package libssl1.1$
> E: Couldn't find any package by glob 'libssl1.1$'
> E: Couldn't find any package by regex 'libssl1.1$'
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package libssl1.0.2$
> E: Couldn't find any package by glob 'libssl1.0.2$'
> E: Couldn't find any package by regex 'libssl1.0.2$'
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package libssl1.0.0$
> E: Couldn't find any package by glob 'libssl1.0.0$'
> E: Couldn't find any package by regex 'libssl1.0.0$'
> Reading package lists...

`libssl` is called `libssl3t64` in Ubuntu 24.04. It is possible their installation script doesn't account for that.

2024-11-16 19:14 UTC, bdellegrazie commented
@npalm I have responded to your questions, please let me know if you require any more information.
Thanks!

2024-11-18 16:40 UTC, npalm commented
@bdellegrazie will check later this week.

2024-11-20 15:55 UTC, npalm requested changes
Thx, tested and works all nice, small remark on the docs.

2024-11-21 07:47 UTC, bdellegrazie commented on examples/multi-runner/README.md
> +- Windows X64 `["self-hosted", "windows", "x64", "servercore-2022"]`: Windows X64 Servercore 2022 runners non ephemeral based on a custom start script.
Fixed

2024-11-21 07:48 UTC, bdellegrazie commented
@npalm I have made the change as requested - could you please re-review?

2025-02-04 15:00 UTC, joemiller commented
GitHub-hosted ubuntu-latest runners are on 24.04 now. This PR hasn't had activity in 2 months. Are there any plans to get this merged to support 24.04?

2025-02-04 23:27 UTC, npalm commented
I will do my best to catch up, something went wrong with merging examples. However this is just about examples. Running with ubuntu 24.04 should not be an issue.

2025-02-06 14:20 UTC, kennedy-whytech commented
@npalm looking forward to upgrading our runners to ubuntu 24.04 to match with the GH-hosted runners. Thanks for pushing this PR. 👍

2025-02-11 11:17 UTC, bdellegrazie commented
@npalm I have rebased and removed unintended documentation changes

2025-03-14 12:33 UTC, bdellegrazie commented
@npalm rebased and re-requested review

2025-05-22 20:44 UTC, bdellegrazie commented
@npalm rebased, could you please re-review?

2025-06-22 08:14 UTC, bdellegrazie commented
@npalm rebased - could you please re-review?

2025-06-23 07:12 UTC, npalm commented
thx for the reminder, put it on my list.

2025-07-01 18:59 UTC, npalm approved these changes

2025-07-01 19:04 UTC, koendelaat approved these changes

2025-07-01 19:12 UTC, merged